#!/usr/local/bin/bash

if [ $# = 0 ] ; then
  echo "Usage: fig2tex file(s).fig"
  exit 1
fi

# C'est tres simple. Le tout est de generer les fichiers avec
# les extensions correctes, afin que pdfLaTeX s'y retrouve aussi
# bien que LaTeX.
#
# Pour mettre les dessins a l'echelle, il suffit de faire
# \scalebox{0.75}{\input{$1.tex}}. 

for t in ${*/.fig/}; do
  echo -n "Creating ../fig/$t[.eps]"
  fig2dev -Lpstex $t.fig ../fig/$t.eps
  echo -n "[.tex]"
  fig2dev -Lpstex_t -p$t $t.fig ../fig/$t.tex
  echo "[.pdf]"
  ../../texinfo/epstopdf ../fig/$t.eps -o=../fig/$t.pdf
done

