set(CTEST_PROJECT_NAME "GetDP")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE_CDASH TRUE)
set(CTEST_DROP_SITE "onelab.info")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=GetDP")
set(CTEST_TRIGGER_SITE "")
