# $Id: Makefile,v 1.3 2001-06-18 07:28:56 geuzaine Exp $

purge:
	for i in fig fig-source; \
        do (cd $$i && $(RM) $(RMFLAGS) *~ *~~ \#*\#); done

clean:
	$(RM) $(RMFLAGS) *.log *.toc *.aux *.dvi *~ *.ps *.pdf

