/* $Id: makehtml.c,v 1.6 2001-10-14 12:09:01 geuzaine Exp $ 
   
   Generate a HTML slide show from a set of image files
*/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

#define HOME         "http://www.geuz.org/getdp/"
#define TOC          "getdp.toc" /* should contain 1 line per slide */
#define INDEX        "getdp.html"
#define POSTSCRIPT   "getdp.ps"
#define PDF          "getdp.pdf"
#define TITLE        "GetDP presentation"
#define AUTHOR       "Christophe Geuzaine"
#define MAXFILES     1000

int  main(int argc, char *argv[]) {
  int i, j, nbfiles;
  char out[MAXFILES][256], toc[MAXFILES][256];
  FILE *file;
  time_t now;
  
  if(argc < 2){
    printf("usage: %s file(s)\n", argv[0]);
    exit(1);
  } 

  time(&now);

  /* create a table containing the output file names */

  for(i=1 ; i<argc ; i++){
    for(j=strlen(argv[i])-1; j>=0; j--){
      if(argv[i][j] == '.'){
	strncpy(out[i-1],argv[i],j);
	out[i-1][j]='\0';
	break;
      }
    }
    if(j<=0) strcpy(out[i-1],argv[i]);
    strcat(out[i-1], ".html");
  }
  nbfiles=argc-1;

  /* create the index */

  for(i=0;i<MAXFILES;i++) strcpy(toc[i],"");

  if(!(file=fopen(TOC, "r"))){
    printf("could not open file '%s'\n", TOC);
  }
  else{
    for(i=0 ; i<nbfiles ; i++)
      fgets(toc[i], 256, file);
  }

  if(!(file=fopen(INDEX, "w"))){
    printf("could not open file '%s'\n", INDEX);
    exit(1);
  }

  printf("creating [%s]", INDEX);

  fprintf(file, 
	  "<HTML>\n"
	  "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n"
	  "<HEAD>\n"
	  "<TITLE>%s - index</TITLE>\n"
	  "<LINK href=\"/general.css\" rel=\"stylesheet\">\n"
	  "</HEAD>\n"
	  "<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\" LINK=\"#0000FF\" VLINK=\"#800080\" ALINK=\"#FF0000\">\n"
	  "<CENTER>\n"
	  "[<A HREF=\"%s\"> Postscript version </A>]<br>\n"
	  "[<A HREF=\"%s\"> PDF version </A>]<br>\n"
	  "<P>\n"
	  "<TABLE cellspacing=0 cellpadding=0>\n",
	  TITLE, POSTSCRIPT, PDF);

  for(i=0 ; i<nbfiles ; i++){
    fprintf(file, 
	    "<TR><TD align=right>[<A HREF=\"%s\"> %d/%d </A>]</TD>",
	    out[i], i+1, nbfiles);
    fprintf(file, 
	    "<TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;%s</TD></TR>\n",
	    toc[i]);
  }

  fprintf(file, 
	  "</TABLE>\n"
	  "<P>\n"
	  "This document was generated by <I>%s</I> on <I>%s</I>\n"
	  "<P>\n"
	  "Back to <a href=\"/\">geuz.org</a>/<a href=\"/getdp/\">getdp</a>"
	  "</CENTER>\n"
	  "</BODY>\n"
	  "</HTML>\n",
	  AUTHOR, ctime(&now));

  fclose(file);

  /* create the output files */
  
  for(i=0 ; i<nbfiles ; i++){

    if(!(file=fopen(out[i], "w"))){
      printf("could not open file '%s'\n", out[i]);
      exit(1);
    }
    
    printf(" [%s]", out[i]);
    if(i==nbfiles-1) printf("\n");
    
    fprintf(file, 
	    "<HTML>\n"
	    "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n"
	    "<HEAD>\n"
	    "<TITLE>%s - %d/%d</TITLE>\n"
	    "<LINK href=\"/general.css\" rel=\"stylesheet\">\n"
	    "</HEAD>\n"
	    "<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\" LINK=\"#0000FF\" VLINK=\"#800080\" ALINK=\"#FF0000\">\n"
	    "<CENTER>\n",
	    TITLE, i+1, nbfiles);

    if(i!=0)
      fprintf(file, 
	      "[<A HREF=\"%s\"> &lt;&lt; </A>]\n"
	      "[<A HREF=\"%s\"> &lt; </A>]\n",
	      out[0], out[i-1]);
    else
      fprintf(file, 
	      "[ &lt;&lt; ]\n"
	      "[ &lt; ]\n");

    fprintf(file, 
	    "[<A HREF=\"%s\"> Index </A>]\n",
	    INDEX);

    if(i==nbfiles-1)
      fprintf(file, 
	      "[ &gt; ]\n"
	      "[ &gt;&gt; ]\n");
    else
      fprintf(file, 
	      "[<A HREF=\"%s\"> &gt; </A>]\n"
	      "[<A HREF=\"%s\"> &gt;&gt; </A>]\n",
	      out[i+1], out[nbfiles-1]);
    
    fprintf(file, 
	    "<P>\n"
	    "<IMG SRC=\"%s\">\n"
            "<P>\n"
	    "Back to <a href=\"/\">geuz.org</a>/<a href=\"/getdp/\">getdp</a>\n"
	    "</CENTER>\n"
	    "</BODY>\n"
	    "</HTML>\n",
	    argv[i+1]);

    fclose(file);

  }

  return 0;
}
