# GetDP - Copyright (C) 1997-2008 P. Dular, C. Geuzaine
#
# See the LICENSE.txt file for license information. Please report all
# bugs and problems to <getdp@geuz.org>.

purge:
	for i in . fig fig-source; do (cd $$i && rm -f *~ *~~ \#*\#); done

clean:
	rm -f *.log *.toc *.aux *.sec *.dvi *~ *.ps *.pdf a.out

