# $Id: Makefile,v 1.6 2003-02-07 10:27:00 geuzaine Exp $

purge:
	for i in fig fig-source; \
        do (cd $$i && rm -f *~ *~~ \#*\#); done

clean:
	rm -f *.log *.toc *.aux *.sec *.dvi *~ *.ps *.pdf a.out

