.\" $Id: getdp.1,v 1.17 2001-03-03 20:03:34 geuzaine Exp $
.\" ======================================================================
.\"
.\" This is the manual page for GetDP
.\" 
.\" Copyright (c) 1998-2001 P. Dular, C. Geuzaine
.\" 
.\" ======================================================================
.TH GetDP 1 "01 March 2001" "Version 0.79" "GetDP Manual Pages"
.UC 4
.\" ======================================================================
.SH NAME
GetDP \- a General environment for the treatment of Discrete Problems
.\" ======================================================================
.SH SYNOPSIS
.B getdp file [option(s)]
.\" ======================================================================
.SH DESCRIPTION
\fIGetDP\fP is a scientific computation software for the numerical
solution of integro-differential equations, using finite element and
integral type methods. \fIGetDP\fP is command-line driven, has no
graphical interface, and works by reading user-written ASCII files
containing the discrete problems definitions, expressed in a way close
to their mathematical formulations.
.\" ======================================================================
.SH WARNING
This man page does not describe the syntax of the ASCII input files:
you should refer to the info documentation for this (e.g. with \fBinfo
getdp\fP). Various versions of the Texinfo manual (html, postscript,
pdf) are available at
\fIhttp://www.geuz.org/getdp/\fP.
.\" ======================================================================
.SH OPTIONS
Here is a description of the most common arguments accepted by
\fIGetDP\fP on the command line:
.TP 4
.B file
is an ASCII file containing the problem definition, i.e.  the
structures the Texinfo documentation will teach you to create. This
file can include other files, so that only one problem definition file
should always be given on the command line. The input files containing
the problem definition structure are usually given the \fI.pro\fP
extension (if so, there is no need to specify the extension on the
command line). The name of this file (without the extension) is used
as a basis for the creation of intermediate files during the
pre-processing and the processing stages.
.TP 4
.B \-pre \fIresolution-id\fP
performs the pre-processing associated with the resolution called
\fIresolution-id\fP. In the pre-processing stage, \fIGetDP\fP creates
the geometric database (from the mesh file), identifies the degrees of
freedom (the unknowns) of the problem and sets up the constraints on
these degrees of freedom. The pre-processing creates a file with 
a \fI.pre\fP extension. If \fIresolution-id\fP is omitted, the list of
available choices is displayed.
.TP 4
.B \-cal
performs the processing. This requires that a pre-processing has been
performed previously, or that a \fB\-pre\fP option is given on the
same command line. The performed resolution is the one given as an
argument to the \fB\-pre\fP option. In the processing stage,
\fIGetDP\fP executes all the operations of the selected resolution
(such as matrix assemblies, system resolutions, ...). The processing
creates a file with a \fI.res\fP extension.
.TP 4
.B \-pos \fIpost-operation-id\fP(s)
performs the post-processing operations selected by the 
\fIpost-operation-id\fP(s). This requires that a processing has been
performed previously, or that a \fB\-cal\fP option is given on the
same command line. If \fIpost-operation-id\fP is omitted, the list of
available choices is displayed.
.TP 4
.B \-ipos \fIpost-processing-id\fP(s)
enters an interactive post-processing mode, permitting to enter
post-processing operations manually. If no \fIpost-processing-id\fP(s)
is (are) given, the list of available choices is displayed.
.TP 4
.B \-msh \fIfilename\fP
reads the mesh database from \fIfilename\fP rather than reading it
from the default problem file name with the \fI.msh\fP extension
appended.
.TP 4
.B \-split
save processing results in separate files (one for each timestep).
.TP 4
.B \-res \fIfilename\fP(s)
load processing results from \fIfilename(s)\fP instead of from the
default problem file name with the \fI.res\fP extension appended.
.TP 4
.B \-adapt \fIfilename\fP(s)
read adaptation constraints from \fIfilename(s)\fP.
.TP 4
.B \-degree \fIfloat\fP
specify maximum interpolation degree.
.TP 4
.B \-log
saves all processing history in a log file (the input file name with
an appended \fI.log\fP extension).
.TP 4
.B \-check
lets you check the problem structure interactively.
.TP 4
.B \-v \fIint\fP
sets the verbosity level. A value of 0 means that no information will
be displayed during the processing. Higher values increase the amount of
information displayed during processing.
.TP 4
.B \-p \fIint\fP
sets the progress update rate. This controls the refreshment rate of
the counter indicating the progress of the current computation.
.TP 4
.B \-info
displays the version information.
.TP 4
.B \-version
displays the version number.
.TP 4
.B \-help
displays a message listing basic usage and available options.
.PP
.\" ======================================================================
.SH AUTHORS
Patrick Dular (Patrick.Dular@ulg.ac.be) and Christophe Geuzaine
(Christope.Geuzaine@ulg.ac.be). Many additions by many other people (see
the info file for a comprehensive list of collaborators).
.\" ======================================================================
.SH SEE ALSO
Texinfo documentation (\fBinfo getdp\fP)
.PP
GetDP web site: \fIhttp://www.geuz.org/getdp/\fP
.PP
GetDP example files in \fI/usr/doc/getdp-0.79/\fR
.PP
Gmsh (a three-dimensional mesh generator with built-in pre- and
post-processing facilities) web site: \fIhttp://www.geuz.org/gmsh/\fP
