# GetDP - Copyright (C) 1997-2011 P. Dular, C. Geuzaine
#
# See the LICENSE.txt file for license information. Please report all
# bugs and problems to <getdp@geuz.org>.

clean:
	rm -f *~ .*~
	cd texinfo && ${MAKE} clean
